name: Pruebas Automáticas

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instala Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instala dependencias
        run: pip install pytest
      - name: Ejecuta pruebas
        run: pytest
